### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by amiltonwong** [guochengqian/PU-GCN#1]
Hi, @guochengqian ,

When will the code be released?

THX!

**Comment by weishuoycbb** [comment]
+1

**Comment by guochengqian** [comment]
Personally, I want to open-source our code. However, the situation is our paper is not accepted, unfortunately. After discussion with my collaborator, we agree to opensource all code and dataset when the paper is accepted.  Thank you for your interest and sorry for the inconvenience

**Comment by siddharthKatageri** [comment]
> Hi, @guochengqian ,
> 
> When will the code be released?
> 
> THX!

+1
Can you please release the dataset atleast?

**Comment by guochengqian** [comment]
hi @siddharthKatageri , 
i have due for ICCV, so i planned to upload it after ICCV. 
but if you guys need it for now, i can upload the draft one (code is not fully cleaned)? if it helps you.

**Comment by siddharthKatageri** [comment]
> hi @siddharthKatageri ,
> i have due for ICCV, so i planned to upload it after ICCV.
> but if you guys need it for now, i can upload the draft one (code is not fully cleaned)? if it helps you.

hi @guochengqian , thanks for the response
yea ICCV is due in 3 days. :sweat_smile:
yes please upload the draft one. It will be of great help.
And also can you please release your PU660 dataset??

**Comment by guochengqian** [comment]
okay. will do tonight

**Comment by guochengqian** [comment]
hi, all. 
The code is released. Our repo can be used to train and evaluate PU-Net, MPU, PU-GAN, and PU-GCN. we also provide code for visualization. 
The pretrained models and dataset PU1K will be released late. I am busy with other deadlines. sorry for the inconvence and thanks all for your interest in PU-GCN.
