### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_lib'

### ISSUE THREAD

**Issue by GabauerDavid** [guochengqian/PU-GCN#2]
Dear Guochenq Qian,

I have set up the environment and installed all necessary packages however I get the following error:
ModuleNotFoundError: No module named 'tf_lib'
I looked through the whole repository but could not find the tf_lib package which should include all methods.
Could it be that this script has not been uploaded yet?

Kind regards,
David

**Comment by guochengqian** [comment]
Dear @GabauerDavid , 
thank you for noticing and pointing it out. I have uploaded the missing parts due to the incorrect .gitignore file. 
cheers, 
Guocheng

**Comment by guochengqian** [comment]
Please let me know if you have any questions about the code.

**Comment by GabauerDavid** [comment]
Dear Guochenq Qian,
I will let you know if I have any questions regarding the code. 
Thanks a lot for your fast response and support.
Cheers,
David
