### ISSUE TITLE
Pretrained-Model

### ISSUE THREAD

**Issue by stevenlin510** [guochengqian/PU-GCN#3]
Hi, thanks for amazing work, could you provide the pre-trained model you have in your paper ? Thanks !
And another question is that did you use monte-carlo sampling to generate the test samples (not ground turth) or use poission-disk sampling ?

**Comment by guochengqian** [comment]
simply train the code on the provided dataset for less than 3 hours, you will have almost the same result as the paper.

**Comment by guochengqian** [comment]
okay. i will release it next week. i am busy with other stuff these days.

**Comment by stevenlin510** [comment]
Thanks !! I just wondering how to get the excellent quantitative results on PUGAN's dataset, it seems that the test samples which PUGAN using were sampled by monte-carlo sampling(2048), and what you might using poisson-disk sampling to generate test sample(2048) right ?

**Comment by guochengqian** [comment]
> Thanks !! I just wondering how to get the excellent quantitative results on PUGAN's dataset, it seems that the test samples which PUGAN using were sampled by monte-carlo sampling(2048), and what you might using poisson-disk sampling to generate test sample(2048) right ?

yes. for comparasion on PU-GAN's dataset, it was not that fair, since the input configuration was not the same.

**Comment by guochengqian** [comment]
FYI, the pre-trained models are released. 
One can also train the models by themselves on PU1K dataset. We support training PU-Net, MPU, PU-GCN. The results are reproducible. We trained 10 times and got close results.

**Comment by lai-pf** [comment]
> 
thanks for sharing the code, which is really generous . 
And may I ask the training settings about PU-Net,MPU,PUGCN model, should I training all these model use the same setting like the default setting you set? or each model has different settings in training?
thanks again
