### ISSUE TITLE
help for evaluate.py

### ISSUE THREAD

**Issue by siddharthKatageri** [guochengqian/PU-GCN#4]
`python evaluate.py --gt "/home/cvgws-04/Interns_CEVI/upsample/PU-Net_pytorch/datas/test_data/our_collected_data/MC_5k" --pred "/home/cvgws-04/Interns_CEVI/upsample/PU-Net_pytorch/outputs/punet_reproduced_batchsize_12/preds" --save_path "/home/cvgws-04/Interns_CEVI/upsample/PU-Net_pytorch/outputs/punet_reproduced_batchsize_12"`

I am trying run evaluate.py provided in your repository.
All ground truth .xyz are in -gt path and the predicted are in -pred path.

I am getting the following error:
`Traceback (most recent call last):
  File "evaluate.py", line 12, in <module>
    from Common.ops import normalize_point_cloud
  File "/home/cvgws-04/Interns_CEVI/upsample/PU-GCN/Common/ops.py", line 4, in <module>
    from tf_ops.grouping.tf_grouping import knn_point_2
  File "/home/cvgws-04/Interns_CEVI/upsample/PU-GCN/tf_ops/grouping/tf_grouping.py", line 10, in <module>
    grouping_module = tf.load_op_library(
  File "/home/cvgws-04/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/cvgws-04/Interns_CEVI/upsample/PU-GCN/tf_ops/grouping/tf_grouping_so.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE`

Please let me know how to resolve.
Thanks in advance.

**Comment by guochengqian** [comment]
tf_ops compilation is not sucessfully. 
For compiling TF operators, please check compile.sh under each op subfolder in `tf_ops` folder. Note that you need to update nvcc, python and tensoflow include library if necessary.
more information, please check: PU-GAN, PU-Net, PointNet.
