### ISSUE TITLE
test code upsampling 16 times

### ISSUE THREAD

**Issue by shashidhar100** [guochengqian/PU-GCN#5]
I executed test_pu1k.sh for pugcn.
the input is 2048 and expected output is 8192,
your provided code in test_pu1k.sh  is upsampling 16 times giving 32768.
i checked the up_ratio argument it is set to 4
please provide your suggestions

**Comment by guochengqian** [comment]
hi, thanks for letting me know. The code was modified for 16 times upsampling to cater to a reviewer's requirement.
I have corrected the code. thank you!
