### ISSUE TITLE
How to test pugan

### ISSUE THREAD

**Issue by BingHan0458** [guochengqian/PU-GCN#7]
Hello, I want to know how to test pugan?Thank you very much!

**Comment by guochengqian** [comment]
please follow : `test_pu1k_allmodels.sh` 

it will be something similar to this, but I did not check

`source test_pu1k.sh pretrain/pugan-pretrain-model/ 0 0 --model pugan --upsampler original`

refer to `test_pu1k.sh` and  `Upsamplings/generator` for details of the arguments
